apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/network-policies/deny-all-policy
- ../base/network-policies/vpn-ingress-policy
- ../base/network-policies/lan-ingress-policy
- ../base/network-policies/cm-allow-resolver-policy
- ../base/network-policies/traefik-ingress-policy
- ../base/middlewares/limit-to-lan
- apps/whoami

patches:
  # add namespace to all policies
- patch: |-
    - op: add
      path: /metadata/namespace
      value: whoami-ns
  target:
    kind: NetworkPolicy
- patch: |-
    - op: add
      path: /metadata/namespace
      value: whoami-ns
  target:
    kind: Middleware
