namespace: nfs-provisioner
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nfs-provisioner-namespace.yaml
- github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy
patches:
- path: truenas-nfs-storage-class-patch.yaml
- path: truenas-nfs-deployment-patch.yaml
