apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nfs-client-provisioner
  name: pvc-nfs-client-root
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      nfs-subdir-external-provisioner: nfs-subdir-external-provisioner
  storageClassName: ""
  resources:
    requests:
      storage: 10Mi

