apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.139.21.199
            - name: NFS_PATH
              value: /mnt/SSDs/external-applications
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
