apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lan-egress-policy
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.139.21.0/24
