apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mosquitto-configmap.yaml
- sealed-mosquitto-password-file.json
- mosquitto-data-nfs-persistentvolumeclaim.yaml
- mosquitto-log-nfs-persistentvolumeclaim.yaml
- mosquitto-deployment.yaml
- mosquitto-service.yaml
# generate an auth token in homeassistant and update this:
# https://github.com/hikhvar/mqtt2prometheus
