apiVersion: v1
kind: Service
metadata:
  annotations:
    volume.storage-class-name: nfs-client
  labels:
    app.kubernetes.io/name: mosquitto
  name: mosquitto
  namespace: smarthome
spec:
  ports:
    - name: "http"
      port: 9001
      targetPort: 9001
    - name: "server"
      port: 1883
      targetPort: 1883
  selector:
    app.kubernetes.io/name: mosquitto
  type: LoadBalancer
status:
  loadBalancer: {}
