apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  createNamespace: true
  targetNamespace: argocd
  valuesContent: |-
    configs:
      params:
        server.insecure: true
    controller:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack

    dex:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack
    redis:
        serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack
    server:
      certificate:
        enabled: true
        domain: cd.rahmed.work
        issuer:
          kind: ClusterIssuer
          name: letsencrypt-prod
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack
    repoServer:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack

    applicationSet:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack

    notifications:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-stack

