kind: Service
apiVersion: v1
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: wireguard
  ports:
  - port: 51820
    nodePort: 31820
    protocol: UDP
    targetPort: 51820
