apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/Helsinki"
  SERVERURL: "85.156.120.36"
  SERVERPORT: "31820"
  PEERS: "3"
  PEERDNS: "10.43.0.10"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "10.139.12.0"
