apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- truenas-namespace.yaml
- ../base/network-policies/deny-all-policy
- ../base/network-policies/vpn-ingress-policy
- ../base/network-policies/lan-ingress-policy
- apps

patches:
  # add namespace to all policies
- patch: |-
    - op: add
      path: /metadata/namespace
      value: truenas
  target:
    kind: NetworkPolicy
