apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lan-ingress-policy
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - ipBlock:
        cidr: 10.139.21.0/24
